# Header
menu:
  首页: /
  档案: archives
  学科: categories
  标签: tags
  关于: about
  留言: guestbook
logo: http://pt2ly2s2i.bkt.clouddn.com/xbl%281%29.png
banner: https://qiniu.miiiku.xyz/src/images/banner.jpg

# banner: css/images/banner.jpg

# large cover
# long: [article, link]
# short: [category, tag]
large_legnth:
  long: 20
  short: 5

# valine 评论
# docs: https://valine.js.org
# You can get your appid and appkey from https://leancloud.cn

valine:
  enable: true
  appId: zU7kuO8tlfD9iuvaskRSfkMR-gzGzoHsz
  appKey: OON0aXU9crNYfzW2blVoiJgH

# dplayer 视频播放
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# zoom 图片预览
# docs: https://github.com/miiiku/zoom
zoom:
  enable: true
  margin: 15
  padding: 15
  radius: 5
  specify:
  filter: "gallery" # filter Front-matter photos

# widget behavior
archive_type: 'monthly'
show_count: false

# beian
beian:

# Miscellaneous
google_analytics:
gauges_analytics:
baidu_analytics:
tencent_analytics:
favicon: /favicon.ico

permalink: false

# 添加萌妹子效果
live2d:
  enable: true
  scriptFrom: local
  model:
    use: live2d-widget-model-wanko    //妹子有很多个，叫名字他才出来
  display:
    position: right   //位置
    width: 150    //妹子宽度
    height: 300    //妹子高度
  mobile:
    show: true
